name: CSPM Security Scan
#this is a testing change
on:
  push:
    paths:
      - 'terraform/**'    # Run when infra changes
  schedule:
    - cron: '0 6 * * *'   # Run daily at 6am UTC
  workflow_dispatch:       # Manual trigger

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: pip install -r scanner/requirements.txt

      - name: Run security scanner
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python scanner/scanner.py

      - name: Upload scan report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: scanner/report.json

      - name: Fail if CRITICAL findings exist
        run: |
          python -c "
          import json, os
          path = 'scanner/report.json'
          if not os.path.exists(path):
            print('No report found - skipping check')
            exit(0)
          with open(path) as f: data = json.load(f)
          criticals = [x for x in data if x.get['severity']=='CRITICAL']
          print(f'Found {len(criticals)} critical findings')
          if criticals: exit(1)  # Fail the pipeline
          "
